# Generated by Django 4.1.7 on 2023-03-24 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='email',
        ),
        migrations.AddField(
            model_name='bio',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='b_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_cart', to='store.products')),
            ],
        ),
    ]
