# Generated by Django 4.1.7 on 2023-03-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('Customer', '0002_remove_bio_email_bio_user_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='kart',
        ),
    ]
