# Generated by Django 4.1.7 on 2023-03-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('Customer', '0004_remove_kart_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='kart',
            name='mobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_cart', to='store.products'),
        ),
    ]
