# Generated by Django 4.1.7 on 2023-03-25 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0005_kart_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kart',
            name='mobile',
        ),
        migrations.AddField(
            model_name='kart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
