# Generated by Django 4.1.7 on 2023-03-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_remove_kart_user_kart_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kart',
        ),
    ]
